name: ROS2 Build & Test

on:
  push:
    branches: [ main, develop ]

jobs:
  build_and_test_ros2:
    runs-on: ubuntu-latest
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: modelec_utils
          target-ros2-distro: jazzy
